# See [Source Acceptance Tests](https://docs.airbyte.com/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-awin:dev
acceptance_tests:
  spec:
    tests:
      - spec_path: "source_awin/spec.yaml"
  connection:
    tests:
      - config_path: "secrets/config.json"
        status: "succeed"
      - config_path: "integration_tests/invalid_config.json"
        status: "failed"
  discovery:
    tests:
      - config_path: "secrets/config.json"
  basic_read:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
        empty_streams:
         - name: "advertiser_transactions"
           bypass_reason: "Sometimes transactions do not exist for the requested time frame. E.g. the account is new, you stopped advertising over a period in time or transactions exist only before the defined start_date."
  incremental: 
    bypass_reason: "This connector does not implement incremental sync"
# TODO uncomment this block this block if your connector implements incremental sync: 
#    tests:
#      - config_path: "secrets/config.json"
#        configured_catalog_path: "integration_tests/configured_catalog.json"
#        future_state_path: "integration_tests/abnormal_state.json"
  full_refresh:
    tests:
      - config_path: "secrets/config.json"
        configured_catalog_path: "integration_tests/configured_catalog.json"
